# TODO : 도커 컴포즈 파일 작성 ( 백엔드 서버 도커 파일 작성 / compose 파일 db 띄우기 )

version: '1.0'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    command: pnpm run start:dev
    depends_on:
      backend_database:
        condition: service_healthy
    ports:
      - '3001:3000'
    env_file:
      - ./backend/.env
    volumes:
      # 개발 중인 소스 코드만 마운트
      - ./backend/src:/usr/src/app/src
      - /usr/src/app/node_modules

  backend_database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '6000:5432'
    volumes:
      - ./backend/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s